version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=health_ai_db
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8008:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data:

  