services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=health_ai_db
    ports:
      - "5432:5432"

  # --- ADD THIS NEW REDIS SERVICE ---
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8008:8000"
    env_file:
      - ./backend/.env
    # --- ADD THIS ENVIRONMENT BLOCK FOR CELERY ---
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # --- ADD THIS NEW CELERY WORKER SERVICE ---
  celery_worker:
    build: ./backend # It uses the same image as the backend
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  ai:
    build: ./ai
    volumes:
      - ./ai:/app
    ports:
      - "8001:8001"

  search:
    image: getmeili/meilisearch:v1.3 # Using a specific version is good practice
    ports:
      - "7700:7700" # Expose Meilisearch default port
    volumes:
      - meili_data:/meili_data
    environment:
      # Use a fixed master key for local development ONLY.
      # NEVER commit this key or use it in production.
      - MEILI_MASTER_KEY=chnadukechachanechandukichachikochandikechamchesechatnichatai
      # Disable analytics for local dev
      - MEILI_NO_ANALYTICS=true

volumes:
  postgres_data:
  meili_data: