"""Add summary column to notes table

Revision ID: 4b7397cf3456
Revises: 62bb34f4b77a
Create Date: 2025-10-18 04:14:17.832271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b7397cf3456"
down_revision: Union[str, Sequence[str], None] = "62bb34f4b77a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "summary")
    # ### end Alembic commands ###
