name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push:
    name: Build, Test, and Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint with flake8
        run: flake8 backend/

      - name: Run backend tests (Placeholder)
        run: echo ">>> Tests would run here <<<"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta # The ID 'meta' is used to reference outputs below
        uses: docker/metadata-action@v5
        with:
          # Define image names (will be prefixed with ghcr.io/OWNER/REPO/)
          images: |
            backend
            ai
          # Generate tags based on git events
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=sha-,format=short

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by 'meta' step
          labels: ${{ steps.meta.outputs.labels }} # Use labels generated by 'meta' step

      - name: Build and push AI Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ai/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by 'meta' step
          labels: ${{ steps.meta.outputs.labels }} # Use labels generated by 'meta'